version: '3'
services:
  proxycache:
    environment:
      - IAM_TOKEN=eyJraWQiOiJyc2ExIiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiI3YTBkZDk4NS0yZmY1LTQ0YzktOTM3My0yYjI2NWQ0NGUxMjEiLCJpc3MiOiJodHRwczpcL1wvZG9kYXMtaWFtLmNsb3VkLmNuYWYuaW5mbi5pdFwvIiwiZXhwIjoxNTU4NDQ0OTczLCJpYXQiOjE1NTg0MzA1NzMsImp0aSI6ImNhYTQ5ZDFlLWRjMTMtNGMwYy05ZjUzLTIwNzRhMzRhM2Q1NCJ9.LNMpHi1Mo2pgJnJR4JXjlBRaJLZZn63RK14d3AZdoJ2_QH3bx8lc9Q0PH-IvZDWVlBIRva_0v3VDDcxVQ0hKBZdvirF_o2E-Q4V6VGbmVwQPjNAL18pHUaiKppY43panAQb9s_GxB4wMbbZdPByFhLmphYk3_0SOR2DiefnrgFU
      - IAM_CLIENT_ID=99f7152a-0550-4be6-8c55-8f27dcbe67e0
      - IAM_CLIENT_SECRET=AIEx7S3vAiIKhinEPndgnEw61GHxMC0k-_4wiVXpLOhLokr97-wNK5PEgMZOpqfO6UkKVARyBb2lQ8i4Qdv_38o
      - CACHE_MANAGER=
      - PROXY_AUDIENCE=https://dodas-tts.cloud.cnaf.infn.it
      - PROXY_TTS=https://dodas-tts.cloud.cnaf.infn.it
      - PROXY_IAM_ENDPOINT=https://dodas-iam.cloud.cnaf.infn.it/
      - PROXY_CREDENTIAL_ENDPOINT=https://dodas-tts.cloud.cnaf.infn.it/api/v2/iam/credential
      - PROXY_LOCAL_CACHE_EXPIRATION_TIME=86400
      - PROXY_LOCK_FILE_AGE=20
      - PROXY_CACHE_DIR=/tmp
    image: "dodasts/ttscache"
    networks:
      testing_net:
        ipv4_address: 172.28.1.4
  cm:
    environment:
      - CONDOR_HOST=172.28.1.1
      - PROXY_CACHE=172.28.1.4
    image: "dodasts/htcondor:v1.0.0.rc1"
    command: master
    networks:
      testing_net:
        ipv4_address: 172.28.1.1    
  schedd:
    environment:
      - IAM_ENDPOINT=https://dodas-iam.cloud.cnaf.infn.it/
      - CLIENT_ID=c53b6a68-c9d5-4320-9f18-6375909b89aa
      - CLIENT_SECRET=AP6d0PQk5Tc1mDFEFMBcGTrqBMsRN3rcqT-FBeFh_ZyQ2sbqSdu5uy16STQAMykkPNHDZyKia3MAzS9rlUNbc7g
      - CONDOR_HOST=172.28.1.1
      - HIGHPORT=2048
      - LOWPORT=1024
      - PROXY_CACHE=172.28.1.4
    image: "dodasts/htcondor:v1.0.0.rc1"
    command: schedd
    volumes:
      - ./config/compose-condormapfile:/home/uwdir/condormapfile
    networks:
      testing_net:
        ipv4_address: 172.28.1.2    
  wn:
    environment:
      - CONDOR_HOST=172.28.1.1
      - CCB_ADDRESS=172.28.1.1
      - PROXY_CACHE=172.28.1.4
    image: "dodasts/htcondor:v1.0.0.rc1"
    command: wn
    networks:
      testing_net:
        ipv4_address: 172.28.1.3    
networks:
    testing_net:
        ipam:
            driver: default
            config:
              - subnet: 172.28.0.0/16                  
